env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:solid/recommended
  - plugin:solid/typescript
  - plugin:prettier/recommended

overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - '@typescript-eslint'
  - solid
  - prettier

rules:
  no-trailing-spaces:
    - error
  eol-last:
    - error
    - always
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always

  # Solid rules
  solid/self-closing-comp:
    - error
    - component: all
      html: all
  solid/no-react-specific-props:
    - error

